[mcp_servers.astro-docs]
url = "https://mcp.docs.astro.build/mcp"

[mcp_servers.chrome-devtools]
args = [
    "chrome-devtools-mcp@latest",
    "--viewport=1440x900",
]
command = "npx"

[mcp_servers.context7]
url = "https://mcp.context7.com/mcp"

[mcp_servers.context7.http_headers]
CONTEXT7_API_KEY = "ctx7sk-15765f5b-18e7-42c5-b873-cda983f7d8f7"

[mcp_servers.sanity]
url = "https://mcp.sanity.io"

[mcp_servers.sanity.http_headers]
Authorization = "Bearer skxuzr9AjzJlYCAed7w2CBsuwysEkRGpfyPkjw84BRWhbl7WhgKa4lhKyhipUu36foZpPwYgz1wvuv3mSVP4NNZ6i03lk2xSJY5Kl3x7viAn0li5LLGOzS0GXOgjjfLp16cEIcMl2B5dIeRwoLLmZcvpBE347EFjMIkGWw0txtPQB5KqIdWZ"
